version: '3.6'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - './app:/usr/src/app'
      - './data:/usr/src/data'
    ports:
      - 8050:8050
    environment:
#      - FLASK_ENV=development
#      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=mysql://wikiuser:mypass@db:3302/wikidump  # new
#      - DATABASE_TEST=mysql+pymysql://wikiuser:mypass@db:3302/wikidump  # new
    depends_on:  # new
      - data
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile-db
    restart: always
    ports:
      - 3306:3306
    environment:
    - MYSQL_DATABASE=wikidump
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - data
    volumes:
#      - './db:/usr/src/db'
      - './data:/usr/src/db/result'

  data:
    build:
      context: ./data
      dockerfile: Dockerfile-data
    volumes:
      - './data:/usr/src/result'
#      - './data:/usr/src/data'



# #TODO
#  nginx:
#    build:
#      context: ./services/nginx
#      dockerfile: Dockerfile-dev
#    restart: always
#    ports:
#    - 80:80
#    depends_on:
#    - users